name: Maven Build Scan Capture
description: Maven Build Scan Capture
author: Gradle team

inputs:
  workflow-name:
    description: 'Name of the workflow triggering the build'
    required: false
    default: ${{ github.workflow }}
  job-name:
    description: 'Name of the job triggering the build'
    required: false
    default: ${{ github.job }}
  maven-home-search-patterns:
    description: 'List of patterns to search for maven home (csv format)'
    required: false
    default: /usr/share/apache-maven-*/,C:/ProgramData/chocolatey/lib/maven/apache-maven-*/
  build-scan-capture-strategy:
    description: 'Build Scan capture strategy (ALWAYS, ON_FAILURE, ON_DEMAND)'
    required: false
    default: ALWAYS
  build-scan-capture-unpublished-enabled:
    description: 'Flag to enable unpublished Build Scan capture'
    required: false
    default: true
  build-scan-capture-link-enabled:
    description: 'Flag to enable Build Scan link capture'
    required: false
    default: true

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js